/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.chrisle.netbeans.plugins.nbscratchfile.components.scratchfilecomponent;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.text.CloneableEditorSupport;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.chrisle.netbeans.plugins.nbscratchfile.components.scratchfilecomponent//ScratchFileComponent//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ScratchFileComponentTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.chrisle.netbeans.plugins.nbscratchfile.components.scratchfilecomponent.ScratchFileComponentTopComponent")
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ScratchFileComponentAction",
        preferredID = "ScratchFileComponentTopComponent"
)
@Messages({
    "CTL_ScratchFileComponentAction=ScratchFileComponent",
    "CTL_ScratchFileComponentTopComponent=ScratchFileComponent Window",
    "HINT_ScratchFileComponentTopComponent=This is a ScratchFileComponent window"
})
public final class ScratchFileTopComponent extends TopComponent {

    public ScratchFileTopComponent() {
        initComponents();
        setName(Bundle.CTL_ScratchFileComponentTopComponent());
        setToolTipText(Bundle.HINT_ScratchFileComponentTopComponent());
    }

    public void setMimeType(String mimeType) {
        String text = scratchEditor.getText();
        scratchEditor.setContentType(mimeType);
        scratchEditor.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        scratchEditor = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();

        scratchEditor.setText(org.openide.util.NbBundle.getMessage(ScratchFileTopComponent.class, "ScratchFileTopComponent.scratchEditor.text")); // NOI18N
        jScrollPane2.setViewportView(scratchEditor);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "text/x-java", "text/x-sql", "text/plain" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        setMimeType("" + jComboBox1.getModel().getSelectedItem());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane scratchEditor;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        //set default mimetype after opening
        //FIXME let the user choose
        setMimeType("text/x-java");
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
